# Generated by Django 5.1.6 on 2025-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_frequency', models.IntegerField()),
                ('income_additional_context', models.TextField()),
                ('assets_type', models.CharField(max_length=100)),
                ('assets_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assets_additional_context', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
