# Generated by Django 5.1.6 on 2025-02-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='assets_additional_context',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='context',
            name='assets_amount',
        ),
        migrations.RemoveField(
            model_name='context',
            name='assets_type',
        ),
        migrations.RemoveField(
            model_name='context',
            name='income_additional_context',
        ),
        migrations.RemoveField(
            model_name='context',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='context',
            name='income_frequency',
        ),
        migrations.RemoveField(
            model_name='context',
            name='location',
        ),
    ]
